name: lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: super-linter
        uses: github/super-linter@v3.14.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
